# Generated by Django 5.1.3 on 2024-12-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_categories_options_alter_categories_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipes",
            name="cooking_time",
        ),
        migrations.AddField(
            model_name="recipes",
            name="cooking_time_hours",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Время приготовления часов"
            ),
        ),
        migrations.AddField(
            model_name="recipes",
            name="cooking_time_minutes",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Время приготовления минут"
            ),
        ),
    ]
